[package]
name = "photo-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
chrono = "0.4"
walkdir = "2.5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }